---
# ufw/tasks/main.yml

- name: Install Packages
  apt: >
    pkg={{ item }}
    state=latest
  with_items:
    - ufw

- name: Allow SSH
  ufw: rule=allow port={{ ansible_ssh_port | default('22') }}

- name: Enable ufw
  ufw: state=enabled logging=on
