---
# ufw/tasks/ssh.yml

- name: Get Current SSH port
  command: 'sed -n -e "s/^\Port\s\+\([0-9]\+\).*/\1/pIi" /etc/ssh/sshd_config'
  register: ufw_current_ssh_port
  changed_when: false
  tags:
    - ufw

- name: Copy App Profile
  include: app_profile.yml
  tags:
    - ufw
  
- name: Update App  Profile
  command: ufw app update AltSSH
  when: ufw_app_profile_title|changed or ufw_app_profile_description|changed or ufw_app_profile_port|changed
  tags:
    - ufw

- name: Set SSH rule
  ufw: >
    rule=allow
    name=AltSSH
  tags:
    - ufw